### ISSUE TITLE
9.5 (51/5) "nonblocking" vs "nonblocking region"

### ISSUE THREAD

**Issue by nholsti** [pat-rogers/Ada-202x-WG9-Informal-Review#158]
Instead of saying "entry body is considered nonblocking", it seems more appropriate to say "entry body is considered a nonblocking region", because "nonblocking region" is the term used in "the above rules".

**Comment by sttaft** [comment]
A nonblocking region is a portion of text.  An entry body is (the body of) a program unit.  So I believe the wording is correct as is.  Furthermore, you could conceivably have another program unit nested within an entry body, and the nonblocking status of that nested program unit would define a new region, which might or might not be nonblocking, since the innermost program unit for the text within it would then be this nested program unit.

**Comment by nholsti** [comment]
Ok, I agree. With the current wording, one first goes to the start of paragraph 43/5 with this entry body as the "innermost enclosing program unit", which then defines the text of the entry body as a nonblocking region (except for nested program units, as you say), to which one can then apply the rules for nonblocking regions. I'll close this issue.
